name: Docker Cleanup Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
        env:
          CI_JOB_ID: ${{ github.run_id }}

      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Start Docker Compose
        run: |
          echo "Starting Docker Compose..."
          docker-compose up -d
          echo "Docker Compose services started."
      
      - name: Build Go Script
        run: |
          go build -o github-detection.go
        env:
          CI_JOB_ID: ${{ github.run_id }}

      - name: Run tests
        run: go test -v ./...

      - name: Wait
        run: sleep 180

      ### No need to run because for now it should be done
      ### manually with local working runner (Github or Gitlab)
      ### This step is unnecessary because it should be done via script 
      ### during clean up after the job is finished
      - name: Stop Docker Compose and Clean Up
        run: |
          echo "Stopping Docker Compose..."
          docker-compose down
          echo "Docker Compose services stopped."